### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by hvalev** [simonMadec/VegAnn#1]
Hi,

I'm interested in trying out this approach for segmenting plant tissue. Do you have or do you plan on releasing a pretrained model?

**Comment by simonMadec** [comment]
Hello @hvalev Yes, I will share it soon

**Comment by simonMadec** [comment]
Hi @hvalev weight of the model here : https://drive.google.com/uc?id=1azagsinfW4btSGaTi0XJKsRnFR85Gtaw
(Unet (resnet34) with weights intialized on imagenet tuned on VegAnn)

Code to try by yourself with colab : https://t.co/LkI1esLzqu

Best
