### ISSUE TITLE
Higher resolution dataset

### ISSUE THREAD

**Issue by Camilochiang** [simonMadec/VegAnn#4]
Hei great paper! thanks.
Would it be possible to get a higher resolution of the dataset? 512 Is quite small considering that the original images must be significantly bigger.

**Comment by simonMadec** [comment]
Considering the labor-intensive and complexity of the annotation process, we have cropped the original images into patches of size 512x512, this has significantly optimized the annotation workflow, also ensuring high-quality results. A total of 989,593,600 pixels are annotated!
